# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
stripe_secret_key: "sk_test_TB8rwlHAlZz59PGJuXJRIwQu"
stripe_publishable_key: "pk_test_o4TqJpzrUAROdBefiM1DQ3pu"
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

#stripe_api_key: "sk_live_dSqzdUq80sw9GWmuoI0qJ9rL"
#stripe_publishable_key: "pk_live_9lcthxpSIHbGwmdO941O1XVU"
# # 